"""paper_engine

Revision ID: 0002
Revises: 0001
"""

from uuid import uuid4

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_counter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_counter")),
    )
    op.create_table(
        "market_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tick", sa.Integer(), nullable=False),
        sa.Column("scenario", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_state")),
    )
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("starting_balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cash_balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("equity", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_return_percent", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high_water_mark", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("max_drawdown_percent", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("day_start_equity", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("week_start_equity", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("day", sa.Date(), nullable=True),
        sa.Column("week", sa.Date(), nullable=True),
        sa.Column("valuation_state", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("cash_balance >= 0", name=op.f("ck_portfolios_nonnegative_cash")),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_portfolios_agent_id_agents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
        sa.UniqueConstraint("agent_id", name=op.f("uq_portfolios_agent_id")),
    )
    op.create_table(
        "benchmarks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("starting_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("equity", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("total_return_percent", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("data_state", sa.String(length=20), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.id"], name=op.f("fk_benchmarks_portfolio_id_portfolios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmarks")),
        sa.UniqueConstraint("portfolio_id", name=op.f("uq_benchmarks_portfolio_id")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("client_order_id", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("requested_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.id"], name=op.f("fk_orders_portfolio_id_portfolios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("portfolio_id", "client_order_id", name=op.f("uq_orders_portfolio_id")),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_portfolio_id"), ["portfolio_id"], unique=False)

    op.create_table(
        "performance_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("equity", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cash", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("market_data_mode", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_performance_snapshots_portfolio_id_portfolios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_performance_snapshots")),
    )
    with op.batch_alter_table("performance_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_performance_snapshots_portfolio_id"), ["portfolio_id"], unique=False
        )

    op.create_table(
        "fills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("requested_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("notional", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("estimated_slippage", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("bid", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("ask", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("market_data_mode", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders")),
        sa.ForeignKeyConstraint(["trade_id"], ["trades.id"], name=op.f("fk_fills_trade_id_trades")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
        sa.UniqueConstraint("order_id", name=op.f("uq_fills_order_id")),
    )
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fills_trade_id"), ["trade_id"], unique=False)

    op.create_table(
        "option_contract_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.id"], name=op.f("fk_option_contract_snapshots_trade_id_trades")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_option_contract_snapshots")),
        sa.UniqueConstraint("trade_id", name=op.f("uq_option_contract_snapshots_trade_id")),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=False),
        sa.Column("asset_type", sa.String(length=30), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("average_entry_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("take_profit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("underlying_symbol", sa.String(length=32), nullable=True),
        sa.Column("option_type", sa.String(length=4), nullable=True),
        sa.Column("strike", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("expiration", sa.Date(), nullable=True),
        sa.Column("contract_multiplier", sa.Integer(), nullable=False),
        sa.Column("entry_iv", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("entry_delta", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("entry_gamma", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("entry_theta", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("entry_vega", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("bid", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("ask", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("data_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_state", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "contract_multiplier > 0", name=op.f("ck_positions_positive_multiplier")
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_positions_nonnegative_quantity")),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.id"], name=op.f("fk_positions_portfolio_id_portfolios")
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.id"], name=op.f("fk_positions_trade_id_trades")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint("trade_id", name=op.f("uq_positions_trade_id")),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_positions_portfolio_id"), ["portfolio_id"], unique=False
        )

    op.create_table(
        "risk_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("rule", sa.String(length=80), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_risk_events_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.id"], name=op.f("fk_risk_events_portfolio_id_portfolios")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_events")),
    )
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_risk_events_portfolio_id"), ["portfolio_id"], unique=False
        )

    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sequence", sa.BigInteger(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f("uq_system_events_sequence"), ["sequence"])

    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.add_column(sa.Column("portfolio_id", sa.Uuid(), nullable=True))
        batch_op.add_column(
            sa.Column("requested_price", sa.Numeric(precision=18, scale=4), nullable=True)
        )
        batch_op.add_column(
            sa.Column("fill_price", sa.Numeric(precision=18, scale=4), nullable=True)
        )
        batch_op.add_column(
            sa.Column("realized_return_percent", sa.Numeric(precision=14, scale=4), nullable=True)
        )
        batch_op.add_column(
            sa.Column("position_size", sa.Numeric(precision=18, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("account_equity_at_entry", sa.Numeric(precision=18, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("percent_allocated", sa.Numeric(precision=14, scale=4), nullable=True)
        )
        batch_op.add_column(
            sa.Column("maximum_planned_loss", sa.Numeric(precision=18, scale=2), nullable=True)
        )
        batch_op.add_column(sa.Column("strategy_name", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("strategy_version", sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column("market_data_mode", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("data_timestamp", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("exit_reason", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("entry_snapshot", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("risk_calculation", sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f("ix_trades_portfolio_id"), ["portfolio_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_trades_portfolio_id_portfolios"), "portfolios", ["portfolio_id"], ["id"]
        )

    # Backfill accounts from existing balances without changing agents or old trades.
    bind = op.get_bind()
    metadata = sa.MetaData()
    agents = sa.Table("agents", metadata, autoload_with=bind)
    portfolios = sa.Table("portfolios", metadata, autoload_with=bind)
    for agent in bind.execute(sa.select(agents)).mappings():
        identifier = uuid4()
        values = dict(
            id=identifier if bind.dialect.name == "postgresql" else identifier.hex,
            agent_id=agent["id"],
            starting_balance=agent["starting_balance"],
            cash_balance=agent["current_balance"],
            market_value=0,
            equity=agent["current_balance"],
            realized_pnl=0,
            unrealized_pnl=0,
            total_return_percent=(agent["current_balance"] / agent["starting_balance"] - 1) * 100,
            high_water_mark=max(agent["starting_balance"], agent["current_balance"]),
            max_drawdown_percent=max(
                0, (1 - agent["current_balance"] / agent["starting_balance"]) * 100
            ),
            day_start_equity=agent["current_balance"],
            week_start_equity=agent["current_balance"],
            valuation_state="unavailable",
        )
        bind.execute(portfolios.insert().values(**values))
    events = sa.Table("system_events", metadata, autoload_with=bind)
    count = 0
    for count, event in enumerate(
        bind.execute(sa.select(events.c.id).order_by(events.c.created_at, events.c.id)), 1
    ):
        bind.execute(events.update().where(events.c.id == event.id).values(sequence=count))
    op.bulk_insert(
        sa.table(
            "event_counter", sa.column("id", sa.Integer()), sa.column("value", sa.BigInteger())
        ),
        [{"id": 1, "value": count}],
    )
    op.bulk_insert(
        sa.table(
            "market_state",
            sa.column("id", sa.Integer()),
            sa.column("tick", sa.Integer()),
            sa.column("scenario", sa.String()),
        ),
        [{"id": 1, "tick": 0, "scenario": "target"}],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_trades_portfolio_id_portfolios"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_trades_portfolio_id"))
        batch_op.drop_column("risk_calculation")
        batch_op.drop_column("entry_snapshot")
        batch_op.drop_column("exit_reason")
        batch_op.drop_column("data_timestamp")
        batch_op.drop_column("market_data_mode")
        batch_op.drop_column("strategy_version")
        batch_op.drop_column("strategy_name")
        batch_op.drop_column("maximum_planned_loss")
        batch_op.drop_column("percent_allocated")
        batch_op.drop_column("account_equity_at_entry")
        batch_op.drop_column("position_size")
        batch_op.drop_column("realized_return_percent")
        batch_op.drop_column("fill_price")
        batch_op.drop_column("requested_price")
        batch_op.drop_column("portfolio_id")

    with op.batch_alter_table("system_events", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_system_events_sequence"), type_="unique")
        batch_op.drop_column("sequence")

    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_events_portfolio_id"))

    op.drop_table("risk_events")
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_portfolio_id"))

    op.drop_table("positions")
    op.drop_table("option_contract_snapshots")
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fills_trade_id"))

    op.drop_table("fills")
    with op.batch_alter_table("performance_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_performance_snapshots_portfolio_id"))

    op.drop_table("performance_snapshots")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_portfolio_id"))

    op.drop_table("orders")
    op.drop_table("benchmarks")
    op.drop_table("portfolios")
    op.drop_table("market_state")
    op.drop_table("event_counter")
    # ### end Alembic commands ###
