"""intelligence

Revision ID: 0003
Revises: 0002
"""

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("benchmarks") as batch_op:
        batch_op.add_column(sa.Column("source_mode", sa.String(20), nullable=True))
        batch_op.add_column(sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column("portfolio_equity_at_start", sa.Numeric(18, 2), nullable=True)
        )
        batch_op.add_column(sa.Column("high_water_price", sa.Numeric(18, 4), nullable=True))
        batch_op.add_column(sa.Column("max_drawdown_percent", sa.Numeric(14, 4), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_budget_guard",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_budget_guard")),
    )
    op.create_table(
        "ai_usage_records",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("estimated_input_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_output_tokens", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("charged_cost", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage_records")),
    )
    with op.batch_alter_table("ai_usage_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_usage_records_scan_id"), ["scan_id"], unique=False)

    op.create_table(
        "event_risks",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("importance", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("warning", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_risks")),
    )
    with op.batch_alter_table("event_risks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_risks_symbol"), ["symbol"], unique=False)

    op.create_table(
        "market_regime_snapshots",
        sa.Column("regime", sa.String(length=30), nullable=False),
        sa.Column("data_mode", sa.String(length=20), nullable=False),
        sa.Column("data_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_regime_snapshots")),
    )
    op.create_table(
        "marketplace_listings",
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("listing_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("asking_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("direct_url", sa.String(length=2000), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_marketplace_listings")),
        sa.UniqueConstraint("source", "listing_id", name=op.f("uq_marketplace_listings_source")),
    )
    op.create_table(
        "provider_status",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("message", sa.String(length=300), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("provider", name=op.f("pk_provider_status")),
    )
    op.create_table(
        "marketplace_analyses",
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("analysis", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_marketplace_analyses_listing_id_marketplace_listings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_marketplace_analyses")),
    )
    with op.batch_alter_table("marketplace_analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_marketplace_analyses_listing_id"), ["listing_id"], unique=False
        )

    op.create_table(
        "marketplace_outcomes",
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_marketplace_outcomes_listing_id_marketplace_listings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_marketplace_outcomes")),
        sa.UniqueConstraint("listing_id", name=op.f("uq_marketplace_outcomes_listing_id")),
    )
    op.create_table(
        "opportunity_candidates",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("components", sa.JSON(), nullable=False),
        sa.Column("regime", sa.String(length=30), nullable=False),
        sa.Column("data_mode", sa.String(length=20), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("rejection_reasons", sa.JSON(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("proposal", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_opportunity_candidates_agent_id_agents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_candidates")),
    )
    with op.batch_alter_table("opportunity_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_opportunity_candidates_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_opportunity_candidates_scan_id"), ["scan_id"], unique=False
        )

    op.create_table(
        "watchlists",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_watchlists_agent_id_agents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlists")),
    )
    with op.batch_alter_table("watchlists", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watchlists_agent_id"), ["agent_id"], unique=False)

    op.create_table(
        "ai_analyses",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("analysis", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["opportunity_candidates.id"],
            name=op.f("fk_ai_analyses_candidate_id_opportunity_candidates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_analyses")),
    )
    with op.batch_alter_table("ai_analyses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_analyses_candidate_id"), ["candidate_id"], unique=False
        )

    op.create_table(
        "shadow_reviews",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("review", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["opportunity_candidates.id"],
            name=op.f("fk_shadow_reviews_candidate_id_opportunity_candidates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shadow_reviews")),
    )
    with op.batch_alter_table("shadow_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shadow_reviews_candidate_id"), ["candidate_id"], unique=False
        )

    op.create_table(
        "watchlist_symbols",
        sa.Column("watchlist_id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlists.id"],
            name=op.f("fk_watchlist_symbols_watchlist_id_watchlists"),
        ),
        sa.PrimaryKeyConstraint("watchlist_id", "symbol", name=op.f("pk_watchlist_symbols")),
    )
    op.create_table(
        "confidence_records",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("predicted_confidence", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("outcome", sa.Boolean(), nullable=True),
        sa.Column("return_percent", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("strategy_version", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("regime", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_confidence_records_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["opportunity_candidates.id"],
            name=op.f("fk_confidence_records_candidate_id_opportunity_candidates"),
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.id"], name=op.f("fk_confidence_records_trade_id_trades")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confidence_records")),
        sa.UniqueConstraint("candidate_id", name=op.f("uq_confidence_records_candidate_id")),
    )
    with op.batch_alter_table("confidence_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_confidence_records_agent_id"), ["agent_id"], unique=False
        )

    op.create_table(
        "opportunity_queue",
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rejection_reason", sa.String(length=1000), nullable=True),
        sa.Column("ai_status", sa.String(length=40), nullable=False),
        sa.Column("shadow_status", sa.String(length=40), nullable=False),
        sa.Column("risk_status", sa.String(length=40), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_opportunity_queue_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["opportunity_candidates.id"],
            name=op.f("fk_opportunity_queue_candidate_id_opportunity_candidates"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_opportunity_queue_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.id"], name=op.f("fk_opportunity_queue_trade_id_trades")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_queue")),
        sa.UniqueConstraint("candidate_id", name=op.f("uq_opportunity_queue_candidate_id")),
    )
    with op.batch_alter_table("opportunity_queue", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_opportunity_queue_agent_id"), ["agent_id"], unique=False
        )

    op.bulk_insert(
        sa.table(
            "ai_budget_guard", sa.column("id", sa.Integer()), sa.column("revision", sa.Integer())
        ),
        [{"id": 1, "revision": 0}],
    )
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("benchmarks") as batch_op:
        for name in [
            "max_drawdown_percent",
            "high_water_price",
            "portfolio_equity_at_start",
            "started_at",
            "source_mode",
        ]:
            batch_op.drop_column(name)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunity_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_opportunity_queue_agent_id"))

    op.drop_table("opportunity_queue")
    with op.batch_alter_table("confidence_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_confidence_records_agent_id"))

    op.drop_table("confidence_records")
    op.drop_table("watchlist_symbols")
    with op.batch_alter_table("shadow_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shadow_reviews_candidate_id"))

    op.drop_table("shadow_reviews")
    with op.batch_alter_table("ai_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_analyses_candidate_id"))

    op.drop_table("ai_analyses")
    with op.batch_alter_table("watchlists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlists_agent_id"))

    op.drop_table("watchlists")
    with op.batch_alter_table("opportunity_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_opportunity_candidates_scan_id"))
        batch_op.drop_index(batch_op.f("ix_opportunity_candidates_agent_id"))

    op.drop_table("opportunity_candidates")
    op.drop_table("marketplace_outcomes")
    with op.batch_alter_table("marketplace_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_marketplace_analyses_listing_id"))

    op.drop_table("marketplace_analyses")
    op.drop_table("provider_status")
    op.drop_table("marketplace_listings")
    op.drop_table("market_regime_snapshots")
    with op.batch_alter_table("event_risks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_risks_symbol"))

    op.drop_table("event_risks")
    with op.batch_alter_table("ai_usage_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_usage_records_scan_id"))

    op.drop_table("ai_usage_records")
    op.drop_table("ai_budget_guard")
    # ### end Alembic commands ###
